#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 22, 2020 06:16:13 PM CST  platform: Windows NT
#    Mar 23, 2020 03:18:12 PM CST  platform: Windows NT
#    Mar 23, 2020 04:00:54 PM CST  platform: Windows NT
#    Mar 23, 2020 04:04:21 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global che76
    che76 = tk.IntVar()
    global che54
    che54 = tk.IntVar()
    global che55
    che55 = tk.IntVar()
    global che67
    che67 = tk.IntVar()
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()





