#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 23, 2020 04:23:05 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1359x741+319+297
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2164 1410
    wm minsize $top 180 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "豆瓣小组帖子筛选器"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo46 \
        -width 1403 -height 1322 -takefocus {} 
    vTcl:DefineAlias "$top.tNo46" "Topics" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo46.t0 \
        -borderwidth 1 -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t0" "Topics_filt" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t0 \
        -padding 0 -sticky nsew -state normal -text 已过滤 -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo46.t0
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr44 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr44" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

    .top43.tNo46.t0.scr44.01 configure -columns "topic_title author_name resp_num time topic_link auhtor_link" \
        -displaycolumns "topic_title author_name resp_num time" \
        -selectmode browse \
        -height 4
        .top43.tNo46.t0.scr44.01 configure -columns {topic_title author_name resp_num time topic_link auhtor_link}
        .top43.tNo46.t0.scr44.01 heading #0 -text {Tree}
        .top43.tNo46.t0.scr44.01 heading #0 -anchor center
        .top43.tNo46.t0.scr44.01 column #0 -width 1262
        .top43.tNo46.t0.scr44.01 column #0 -minwidth 20
        .top43.tNo46.t0.scr44.01 column #0 -stretch 1
        .top43.tNo46.t0.scr44.01 column #0 -anchor w
        .top43.tNo46.t0.scr44.01 heading topic_title -anchor center
        .top43.tNo46.t0.scr44.01 column topic_title -width 698
        .top43.tNo46.t0.scr44.01 column topic_title -minwidth 20
        .top43.tNo46.t0.scr44.01 column topic_title -stretch 1
        .top43.tNo46.t0.scr44.01 column topic_title -anchor w
        .top43.tNo46.t0.scr44.01 heading author_name -anchor center
        .top43.tNo46.t0.scr44.01 column author_name -width 703
        .top43.tNo46.t0.scr44.01 column author_name -minwidth 20
        .top43.tNo46.t0.scr44.01 column author_name -stretch 1
        .top43.tNo46.t0.scr44.01 column author_name -anchor w
        .top43.tNo46.t0.scr44.01 heading resp_num -anchor center
        .top43.tNo46.t0.scr44.01 column resp_num -width 700
        .top43.tNo46.t0.scr44.01 column resp_num -minwidth 20
        .top43.tNo46.t0.scr44.01 column resp_num -stretch 1
        .top43.tNo46.t0.scr44.01 column resp_num -anchor w
        .top43.tNo46.t0.scr44.01 heading time -anchor center
        .top43.tNo46.t0.scr44.01 column time -width 701
        .top43.tNo46.t0.scr44.01 column time -minwidth 20
        .top43.tNo46.t0.scr44.01 column time -stretch 1
        .top43.tNo46.t0.scr44.01 column time -anchor w
        .top43.tNo46.t0.scr44.01 heading topic_link -anchor center
        .top43.tNo46.t0.scr44.01 column topic_link -width 200
        .top43.tNo46.t0.scr44.01 column topic_link -minwidth 20
        .top43.tNo46.t0.scr44.01 column topic_link -stretch 1
        .top43.tNo46.t0.scr44.01 column topic_link -anchor w
        .top43.tNo46.t0.scr44.01 heading auhtor_link -anchor center
        .top43.tNo46.t0.scr44.01 column auhtor_link -width 200
        .top43.tNo46.t0.scr44.01 column auhtor_link -minwidth 20
        .top43.tNo46.t0.scr44.01 column auhtor_link -stretch 1
        .top43.tNo46.t0.scr44.01 column auhtor_link -anchor w
    vTcl:copy_lock $site_4_0.scr44
    place $site_4_0.scr44 \
        -in $site_4_0 -x 0 -y 0 -width 3227 -relwidth 1 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    frame $top.tNo46.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t1" "Topics_bad_author" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t1 \
        -padding 0 -sticky nsew -state normal -text 中介贴 -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo46.t1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr44 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_1.scr44" "Scrolledtreeview2" vTcl:WidgetProc "Toplevel1" 1

    .top43.tNo46.t1.scr44.01 configure -columns "topic author response time is_bad_author" \
        -height 4
        .top43.tNo46.t1.scr44.01 configure -columns {topic author response time is_bad_author}
        .top43.tNo46.t1.scr44.01 heading #0 -text {Tree}
        .top43.tNo46.t1.scr44.01 heading #0 -anchor center
        .top43.tNo46.t1.scr44.01 column #0 -width 200
        .top43.tNo46.t1.scr44.01 column #0 -minwidth 20
        .top43.tNo46.t1.scr44.01 column #0 -stretch 1
        .top43.tNo46.t1.scr44.01 column #0 -anchor w
        .top43.tNo46.t1.scr44.01 heading topic -anchor center
        .top43.tNo46.t1.scr44.01 column topic -width 200
        .top43.tNo46.t1.scr44.01 column topic -minwidth 20
        .top43.tNo46.t1.scr44.01 column topic -stretch 1
        .top43.tNo46.t1.scr44.01 column topic -anchor w
        .top43.tNo46.t1.scr44.01 heading author -anchor center
        .top43.tNo46.t1.scr44.01 column author -width 200
        .top43.tNo46.t1.scr44.01 column author -minwidth 20
        .top43.tNo46.t1.scr44.01 column author -stretch 1
        .top43.tNo46.t1.scr44.01 column author -anchor w
        .top43.tNo46.t1.scr44.01 heading response -anchor center
        .top43.tNo46.t1.scr44.01 column response -width 200
        .top43.tNo46.t1.scr44.01 column response -minwidth 20
        .top43.tNo46.t1.scr44.01 column response -stretch 1
        .top43.tNo46.t1.scr44.01 column response -anchor w
        .top43.tNo46.t1.scr44.01 heading time -anchor center
        .top43.tNo46.t1.scr44.01 column time -width 200
        .top43.tNo46.t1.scr44.01 column time -minwidth 20
        .top43.tNo46.t1.scr44.01 column time -stretch 1
        .top43.tNo46.t1.scr44.01 column time -anchor w
        .top43.tNo46.t1.scr44.01 heading is_bad_author -anchor center
        .top43.tNo46.t1.scr44.01 column is_bad_author -width 200
        .top43.tNo46.t1.scr44.01 column is_bad_author -minwidth 20
        .top43.tNo46.t1.scr44.01 column is_bad_author -stretch 1
        .top43.tNo46.t1.scr44.01 column is_bad_author -anchor w
    place $site_4_1.scr44 \
        -in $site_4_1 -x 0 -relx 0.16 -y 0 -rely 0.28 -width 0 \
        -relwidth 0.515 -height 0 -relheight 0.158 -anchor nw \
        -bordermode ignore 
    frame $top.tNo46.t2 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t2" "Topics_bad_word" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t2 \
        -padding 0 -sticky nsew -state normal -text 垃圾帖 -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo46.t2
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_2.scr60 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_2.scr60" "Scrolledlistbox3" vTcl:WidgetProc "Toplevel1" 1

    $site_4_2.scr60.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -takefocus 0 \
        -width 10
    place $site_4_2.scr60 \
        -in $site_4_2 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    frame $top.tNo46.t3 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t3" "Topics_readed" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo46 add $top.tNo46.t3 \
        -padding 0 -sticky nsew -state normal -text 已读 -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo46.t3
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_3.scr61 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_3.scr61" "Scrolledlistbox4" vTcl:WidgetProc "Toplevel1" 1

    $site_4_3.scr61.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -takefocus 0 \
        -width 10
    place $site_4_3.scr61 \
        -in $site_4_3 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    labelframe $top.lab45 \
        -font TkDefaultFont -foreground black -text 抓取帖子设置 \
        -background $vTcl(actual_gui_bg) -height 174 -width 435 
    vTcl:DefineAlias "$top.lab45" "grabing_setting" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab45
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_3_0.ent48" "douban_id_input" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {输入豆瓣小组id  } 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_3_0.ent50" "stop_time" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {输入截止时间     } 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_3_0.ent52" "max_pages" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 输入最大抓取页数 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 抓取至上次时间 -variable che54 
    vTcl:DefineAlias "$site_3_0.che54" "isTillLastTime" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 限制最大抓取页数 -variable che55 
    vTcl:DefineAlias "$site_3_0.che55" "isMaxPageLim" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.195 -width 204 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.172 -width 0 \
        -relwidth 0.368 -height 0 -relheight 0.178 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.35 -width 204 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.368 -height 0 -relheight 0.178 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.506 -width 204 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.584 -y 0 -rely 0.506 -width 0 \
        -relwidth 0.368 -height 0 -relheight 0.178 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che54 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.7 -height 0 \
        -relheight 0.14 -anchor nw -bordermode ignore 
    place $site_3_0.che55 \
        -in $site_3_0 -x 0 -relx 0.488 -y 0 -rely 0.7 -width 0 \
        -relwidth 0.427 -height 0 -relheight 0.14 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab56 \
        -font TkDefaultFont -foreground black -text 帖子过滤设置 \
        -background $vTcl(actual_gui_bg) -height 252 -width 435 
    vTcl:DefineAlias "$top.lab56" "filter_setting" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab56
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -height 30 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 显示或添加作者黑名单 
    vTcl:DefineAlias "$site_3_0.but57" "show_add_bad_author" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 显示或添加过滤关键词 
    vTcl:DefineAlias "$site_3_0.but58" "show_add_bad_word" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 显示添加关键词白名单 
    vTcl:DefineAlias "$site_3_0.but59" "show_add_good_word" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 显示或添加作者白名单 
    vTcl:DefineAlias "$site_3_0.but60" "show_add_good_author" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent61" "ety_bad_author" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 184 
    vTcl:DefineAlias "$site_3_0.ent62" "ety_good_author" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent63" "ety_bad_word" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent64 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 184 
    vTcl:DefineAlias "$site_3_0.ent64" "ety_good_word" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent65 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent65" "ety_max_topic" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text 最大发帖数 
    vTcl:DefineAlias "$site_3_0.lab66" "Label4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 使用发帖数限制 -variable che67 
    vTcl:DefineAlias "$site_3_0.che67" "isByTopicNum" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent69" "ety_max_response" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 最大回复数 
    vTcl:DefineAlias "$site_3_0.lab70" "Label4_1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 使用回复数限制 -variable che76 
    vTcl:DefineAlias "$site_3_0.che76" "isByResposeNum" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but57 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.239 -width 193 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.478 -width 193 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.529 -y 0 -rely 0.478 -width 181 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.529 -y 0 -rely 0.239 -width 183 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.137 -width 194 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 0 -relx 0.529 -y 0 -rely 0.119 -width 184 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.375 -width 194 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 0 -relx 0.529 -y 0 -rely 0.375 -width 184 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.299 -y 0 -rely 0.685 -width 124 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.685 -width 0 \
        -relwidth 0.244 -height 0 -relheight 0.103 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che67 \
        -in $site_3_0 -x 0 -relx 0.598 -y 0 -rely 0.685 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 0 -relx 0.299 -y 0 -rely 0.788 -width 124 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.788 -width 0 \
        -relwidth 0.244 -height 0 -relheight 0.103 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che76 \
        -in $site_3_0 -x 0 -relx 0.598 -y 0 -rely 0.794 -width 0 \
        -relwidth 0.361 -height 0 -relheight 0.087 -anchor nw \
        -bordermode ignore 
    button $top.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 加载本地记录 
    vTcl:DefineAlias "$top.but72" "load_in_file" vTcl:WidgetProc "Toplevel1" 1
    button $top.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 抓取并筛选帖子 
    vTcl:DefineAlias "$top.but73" "get_on_douban" vTcl:WidgetProc "Toplevel1" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 重新筛选帖子 
    vTcl:DefineAlias "$top.but75" "filter_records" vTcl:WidgetProc "Toplevel1" 1
    button $top.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ab3048 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text 保存并退出 
    vTcl:DefineAlias "$top.but77" "save_exit" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo46 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.01 -width 0 -relwidth 0.64 \
        -height 0 -relheight 0.99 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.055 -width 0 -relwidth 0.32 \
        -height 0 -relheight 0.235 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.662 -y 0 -rely 0.31 -width 0 -relwidth 0.32 \
        -height 0 -relheight 0.34 -anchor nw -bordermode ignore 
    place $top.but72 \
        -in $top -x 0 -relx 0.662 -y 0 -rely 0.661 -width 435 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but73 \
        -in $top -x 0 -relx 0.662 -y 0 -rely 0.729 -width 435 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.662 -y 0 -rely 0.796 -width 435 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.662 -y 0 -rely 0.864 -width 437 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

